name: venv  # Change this to your desired environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python  # Ensures Python is installed
  - numpy
  - pandas
  - matplotlib
  - scipy
  - plotly
  - dash
  # Uncomment below if needed
  # - opencv  # For shadowgraph list
  # - tator   # Only if working with Tator
  # - jupyter # Only for Jupyter notebooks
